//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.webServicePrueba {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pieza", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary2")]
    [System.SerializableAttribute()]
    public partial class Pieza : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlcanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DanioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float VidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Alcance {
            get {
                return this.AlcanceField;
            }
            set {
                if ((this.AlcanceField.Equals(value) != true)) {
                    this.AlcanceField = value;
                    this.RaisePropertyChanged("Alcance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Danio {
            get {
                return this.DanioField;
            }
            set {
                if ((this.DanioField.Equals(value) != true)) {
                    this.DanioField = value;
                    this.RaisePropertyChanged("Danio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Movimiento {
            get {
                return this.MovimientoField;
            }
            set {
                if ((this.MovimientoField.Equals(value) != true)) {
                    this.MovimientoField = value;
                    this.RaisePropertyChanged("Movimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unidad {
            get {
                return this.UnidadField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadField, value) != true)) {
                    this.UnidadField = value;
                    this.RaisePropertyChanged("Unidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Vida {
            get {
                return this.VidaField;
            }
            set {
                if ((this.VidaField.Equals(value) != true)) {
                    this.VidaField = value;
                    this.RaisePropertyChanged("Vida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary2")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ConectadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Conectado {
            get {
                return this.ConectadoField;
            }
            set {
                if ((this.ConectadoField.Equals(value) != true)) {
                    this.ConectadoField = value;
                    this.RaisePropertyChanged("Conectado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="webServicePrueba.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setPieza", ReplyAction="http://tempuri.org/IService1/setPiezaResponse")]
        WebApplication1.webServicePrueba.Pieza setPieza(WebApplication1.webServicePrueba.Pieza pieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPieza", ReplyAction="http://tempuri.org/IService1/getPiezaResponse")]
        string getPieza();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setUsuario", ReplyAction="http://tempuri.org/IService1/setUsuarioResponse")]
        string setUsuario(WebApplication1.webServicePrueba.Usuario user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsuarios", ReplyAction="http://tempuri.org/IService1/getUsuariosResponse")]
        string getUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/invocarGrafo", ReplyAction="http://tempuri.org/IService1/invocarGrafoResponse")]
        void invocarGrafo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminarUsuario", ReplyAction="http://tempuri.org/IService1/eliminarUsuarioResponse")]
        string eliminarUsuario(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modificarUsuario", ReplyAction="http://tempuri.org/IService1/modificarUsuarioResponse")]
        string modificarUsuario(string nickname, string nicknameNuevo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modificarContrasenia", ReplyAction="http://tempuri.org/IService1/modificarContraseniaResponse")]
        string modificarContrasenia(string nickname, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modificarCorreo", ReplyAction="http://tempuri.org/IService1/modificarCorreoResponse")]
        string modificarCorreo(string nickname, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modificarEstad", ReplyAction="http://tempuri.org/IService1/modificarEstadResponse")]
        string modificarEstad(string nickname, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscarUsuario", ReplyAction="http://tempuri.org/IService1/buscarUsuarioResponse")]
        WebApplication1.webServicePrueba.Usuario buscarUsuario(string nickname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication1.webServicePrueba.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication1.webServicePrueba.IService1>, WebApplication1.webServicePrueba.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public WebApplication1.webServicePrueba.Pieza setPieza(WebApplication1.webServicePrueba.Pieza pieza) {
            return base.Channel.setPieza(pieza);
        }
        
        public string getPieza() {
            return base.Channel.getPieza();
        }
        
        public string setUsuario(WebApplication1.webServicePrueba.Usuario user) {
            return base.Channel.setUsuario(user);
        }
        
        public string getUsuarios() {
            return base.Channel.getUsuarios();
        }
        
        public void invocarGrafo() {
            base.Channel.invocarGrafo();
        }
        
        public string eliminarUsuario(string nickname) {
            return base.Channel.eliminarUsuario(nickname);
        }
        
        public string modificarUsuario(string nickname, string nicknameNuevo) {
            return base.Channel.modificarUsuario(nickname, nicknameNuevo);
        }
        
        public string modificarContrasenia(string nickname, string contrasenia) {
            return base.Channel.modificarContrasenia(nickname, contrasenia);
        }
        
        public string modificarCorreo(string nickname, string correo) {
            return base.Channel.modificarCorreo(nickname, correo);
        }
        
        public string modificarEstad(string nickname, bool estado) {
            return base.Channel.modificarEstad(nickname, estado);
        }
        
        public WebApplication1.webServicePrueba.Usuario buscarUsuario(string nickname) {
            return base.Channel.buscarUsuario(nickname);
        }
    }
}
